"""empty message

Revision ID: 981a786d2ab6
Revises: 2087a1db8595
Create Date: 2023-01-31 17:49:37.367628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981a786d2ab6'
down_revision = '2087a1db8595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignments', 'state',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignments', 'state',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    # ### end Alembic commands ###
